version: "3.8"

services:
    frontend:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "3001:80"
        environment:
            REACT_APP_API_URL: "http://localhost:3000/api"
