version: "3.8"

services:
    frontend:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                - REACT_APP_API_URL=http://localhost:3000/api
        ports:
            - "3001:3001"
